### ISSUE TITLE
Deployment does not generate the appimages.json or versions.json metadata

### ISSUE THREAD

**Issue by pchote** [Fauntleroy/openra-web#12]
https://github.com/OpenRA/openra.github.io shows the expected layout for the deployed site.

Here's a stripped down hack I use for another project that keeps an orphaned gh-pages branch with the compiled output that doesn't share content with the master branch. This might be a useful base to start with:

```yaml
name: Deploy Website

on:
  push:
    branches:
      - master

jobs:
  linux:
    name: Deploy Website
    runs-on: ubuntu-18.04
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Compile and Deploy
        run: |
          git fetch origin
          git checkout --orphan gh-pages
          git rm -rf .
          git checkout master -- <any files that we want to preserve from the master branch>
          # <Commands to generate the new branch structure>
          git config --local user.email "foo@foo.foo"
          git config --local user.name "foo"
          git add --all
          git commit -m "Deploy to GitHub Pages"
          git push origin +gh-pages
```
